name: Push Pre-Release

on:
  push:
    branches:
      - jobs-pre-release
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: push dev tag
        run: |
          git tag -f dev
          git push -f origin dev
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: create bin directory
        run: mkdir -p bin
      - name: Build binary
        run: go build -o bin/kyma-test
        # TODO: build for all platforms
      - name: Create pre-release
        uses: actions/github-script@v7
        with:
          result-encoding: string
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/scripts/create-pre-release.js');
            script({github, context});
